### ISSUE TITLE
bug(flutter-styles): renome TextStyles to another name

### ISSUE THREAD

**Issue by paulononaka** [FacioCode/design#34]
@jimmyandrade the name TextStyles is reserved to an official Flutter library so it must be changed.

https://github.com/FacioCode/design/blob/3f9a5b9a74cb1e20078b5cf3e04ae3bc50aff8d0/packages/flutter-styles/lib/text_theme.dart#L13

**Comment by paulononaka** [comment]
Never mind. Actually `TextStyle` is used, not `TextStyles`.

**Comment by jimmyandrade** [comment]
@paulononaka I could rename it to `TypographyStyles`, WDYT?
